= Docker Grundlagen

== Virtuelle Maschinen und Container

=== Virtuelle Maschinen

* In einer Virtuellen Maschine wird das gesamte Betriebssystem virtualisiert
* Die zugrundeliegende Hardware wird ebenfalls vom Hypervisor _errechnet_
* Eine VM ist somit sehr vielseitig einsetzbar, in der Regel kann darin unabhängig vom Betriebssystem des Hosts (des Rechners, auf dem die Virtualisierungssoftware, z.B. _HyperV_ läuft) jedes anderer Betriebssystem virtualisiert werden
* In einer VM laufen eine Vielzahl an Programmen
* Die gesamte VM läuft _isoliert_ vom Rest des Systems, im Groben vergleichbar mit einer _Sandbox_

=== (Docker) Container

* Bei Containern ist man an das Betriebssystem des Hosts gebunden
* Grund dafür ist, dass Container z.B. den Kernel und weitere Resourcen des Hostsystems nutzen
* Hieraus folgen sowohl große Vorteile als auch gewisse Nachteile
* Container sind *sehr* leichtgewichtig im Vergleich zu VMs
* es können problemlos zig bis hundert oder sogar tausende Container auf einem Host ausgeführt werden
* Container starten extrem schnell
* In einem Container läuft in der Regel *eine* Anwendung (z.B. ein Webserver, ein Datenbanksystem, eine _Nextcloud_ usw.)
* Auch Container sind zu einem bestimmten Teil vom Hostsystem isoliert, Prozesse innerhalb der Container können zwar vom Hostsystem aus geshen werden, Prozesse innerhalb der Container haben aber keine Kenntnis von Prozessen des Hostsystems

=== Images

* Images sind die Bauvorlagen für Container
* Images können z.B. vom Docker Hub heruntergeladen werden
* aus einem Image können beliebig viele Container gebaut werden

=== Netzwerk und Portforwarding

* Docker Container befinden sich innerhalb eines privaten Netzwerks welches vom Docker Daemon verwaltet wird
* Container können sich untereinander _sehen_ bzw. erreichen, sind aber ohne weiteres nicht von _außen_ erreichbar
* Um z.B. eine Webapplikation wie _Nextcloud_ von außen verfügbar zu machen, wird _Port Forwarding_ genutzt
* Hier wird z.B. der _interne_ Port 80 (also der Port *innerhalb* des Containers) mit dem _äußeren_ Port 8080 (oder einem anderen freien Port) verbunden
* So ist der Container dann beispielsweise über die Adresse https://meine.ip:8080 erreichbar
