version: '2'

volumes:
  nextcloud:
  db:

# unsere Container
services:

  app:
    image: nextcloud:fpm
    restart: always
    volumes:
      - ./nextcloud-data:/var/www/html
    links:
      - db
    environment:
      - MYSQL_PASSWORD=cloudiuspw
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=cloudius
      - MYSQL_HOST=db

  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwdb
      - MYSQL_PASSWORD=cloudiuspw
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=cloudius

  webserver:
    image: nginx
    # Docker versucht den Container neu zu starten falls er z.B. crashed
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - app
    # Zugriff auf die Volumes des nextcloud containers
    # nötig, damit die Dateien vom Webserver ausgeliefert
    # werden können
    volumes_from:
      - app
